from datetime import datetime
from decimal import Decimal
from pydantic import BaseModel, Field, ConfigDict
from app.db.models import RequisitionStatus

# 1 - template ---------------
# CREATE REQUEST SCHEMAS
class RequisitionItemCreate(BaseModel):
    """
    Represents one item submitted when creating a requisition.

    This schema is used to validate incoming API data before
    anything is written to the database.
    """

    description: str = Field(
        min_length=10,
        max_length=500,
    )

    quantity: int = Field(
        gt=0,
    )

    unit: str = Field(
        min_length=1,
        max_length=50,
    )

    estimated_rate: Decimal = Field(
        gt=0,
        max_digits=12,
        decimal_places=2,
    )

# id from jwt
class RequisitionCreate(BaseModel):
    """
    Request body for POST /api/requisitions.

    requested_by is intentionally NOT accepted from the client.
    The requester is taken from the authenticated JWT user.
    """

    project_name: str = Field(
        min_length=1,
        max_length=200,
    )

    department: str = Field(
        min_length=1,
        max_length=100,
    )

    items: list[RequisitionItemCreate] = Field(
        min_length=1,
    )

# 2 - template ---------------
# NORMAL REQUISITION RESPONSE
class RequisitionItemResponse(BaseModel):
    """
    Represents an item returned from the SQLAlchemy ORM model.
    """

    id: int
    description: str
    quantity: Decimal
    unit: str
    estimated_rate: Decimal

    model_config = ConfigDict(from_attributes=True)

class RequisitionResponse(BaseModel):
    """
    Full requisition response used by the create endpoint.

    This mirrors the SQLAlchemy Requisition model and its
    related RequisitionItem records.
    """
    id: int
    requisition_no: str
    project_name: str
    requested_by: int
    department: str
    status: RequisitionStatus
    created_at: datetime
    items: list[RequisitionItemResponse]

    model_config = ConfigDict(from_attributes=True)

# 3 - template ---------------
# DETAIL RESPONSE
class RequisitionDetailItemResponse(BaseModel):
    """
    Represents an item returned by the PostgreSQL JSON function.

    Notice that this is different from RequisitionItemResponse.

    The stored function returns:
        qty
        rate
        total

    rather than the ORM field names:
        quantity
        estimated_rate

    'total' is calculated by PostgreSQL.
    """
    description: str
    qty: Decimal
    unit: str
    rate: Decimal
    total: Decimal

class RequisitionDetailResponse(BaseModel):
    """
    Response for GET /api/requisitions/{id}.

    This schema matches the JSON structure generated by
    usp_get_requisition() in PostgreSQL.
    """
    requisition_no: str = Field(alias="requisitionNo")
    project: str
    requested_by: int = Field(alias="requestedBy")
    department: str
    status: RequisitionStatus
    created_date: datetime = Field(alias="createdDate")
    items: list[RequisitionDetailItemResponse]

    model_config = ConfigDict(populate_by_name=True)

# 4 ---------------
# LIST RESPONSE
class RequisitionListResponse(BaseModel):
    """
    Lightweight response for GET /api/requisitions.

    We don't return the items here because the list screen
    only needs summary information.
    """
    id: int
    requisition_no: str
    project_name: str
    requested_by: int
    department: str
    status: RequisitionStatus
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)
