"""add is embedded to requisitions

Revision ID: f87a8dfa50a1
Revises: ad60a4d96dfc
Create Date: 2026-08-18 05:40:38.531380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f87a8dfa50a1"
down_revision: Union[str, Sequence[str], None] = "ad60a4d96dfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "requisitions",
        sa.Column(
            "is_embedded",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )

    op.alter_column(
        "requisitions",
        "is_embedded",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requisitions", "is_embedded")
    # ### end Alembic commands ###
